import { Rubik } from "next/font/google";
import './styles/global.css';
import RootProvider from "@/components/common/provider";
import { Toaster } from 'sonner';
import { CartProvider } from "@/contexts/CartContext";
import { CookiesProvider } from "react-cookie"; // 🍪 SHU QATORNI QO‘SHING

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-rubik",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-sans antialiased bg-gray-300 ${rubik.className}`}>
        <CookiesProvider> {/* 🍪 CookiesProvider bilan o‘raldi */}
          <RootProvider>
            <CartProvider>
              {children}
              <Toaster />
            </CartProvider>
          </RootProvider>
        </CookiesProvider>
      </body>
    </html>
  );
}
