import { Rubik } from "next/font/google";
import "./styles/global.css";
import ClientWrapper from "@/components/common/client-wrapper"; // ✅ Faqat buni ishlatamiz

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-rubik",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans antialiased bg-gray-300 ${rubik.className}`}>
        <ClientWrapper>{children}</ClientWrapper> {/* ✅ SHU */}
      </body>
    </html>
  );
}
