import { Rubik } from "next/font/google";
import './styles/global.css';
import RootProvider from "@/components/common/provider"; // Adjust this import path as needed
import { Toaster } from 'sonner'; // or from your chosen toast library
import Siteheader from "@/components/common/site-header";
import Footer from "@/components/ui/footer";
import { CartProvider } from "@/contexts/CartContext";

const rubik = Rubik({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-rubik",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`font-sans antialiased bg-gray-300 ${rubik.className}`}>
        <RootProvider>
       <CartProvider>
          {children}
          <Toaster />
          </CartProvider>
        </RootProvider>
      </body>
    </html>
  );
}